#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#define MAX 60
/*
	Johnny Rivera
	CSC 362-001
	This program simulates the Hare and Tortoise race that many know of. The
	path that they race on is defined in path[] where there are the blank spaces,
	"R", "S", and "C" characters. Each animal goes through the same path with different speeds.
	The hare moves 1 to 8 spaces per turn while the tortoise moves 1 to 3 spots each turn.
	These characters have different effects depending onthe animal that lands on it. If the
	hare lands in the "R" and the "S" spaces they have to go back until they are no longer on
	them. If the hare lands on a "C" they have to take a 1 turn break and wont move while removing the C
	to show that the hare has eaten the carrot. In addition the hare as a 1 in 4 chance to take a nap
	and lose a turn.The code uses array pointers to locate information at the address needed in order 
	to update the information to print to the terminal. 
*/

// PROTOTYPES
// This function takes in the Tortoise pointer, Hare Pointer, and the Collision Pointer
// to update the race focusing on the tortoise's position.
char* moveTortoise(char*, char*, int*);

// This function takes in the path array, Tortoise Pointer, Nap Pointer,
// and Collision Pointer to update the race focusing on the hare's position.
char* moveHare(char[], char*, char*, int*, int*);

// This function takes in the path pointer, hare pointer, tortoise pointer, turn value, collision value,
// and nap value to print the current race update to the terminal with the required information.
void print(char *, char*, char*, int, int, int);

/*
This main function calls upon the two move hare/torttoise functions and the void print statement.
The main purpose of this function is to initialize the code and set variables/data to their corresponding
locations. There is a while loop that iterates through the functions while the hare (H) and the tortoise (T) have not
reached the end (path +  MAX). As long as the hare does not land on a "C" or carrot it will procede to call the function
to determine the positions to move.
*/
void main() 
{
	char path[] = " R  R  R  SSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R ";
	char* T = path;
	char* H = path;
	int turn = 1; 
	int collision = 0; 
	int nap = 0; 
	srand(time(0));
	while ((H < path + MAX) && (T < path + MAX)) 
	{
		T = moveTortoise(T, H, &collision); 
		if (*H != 'C'){H = moveHare(path, H, T, &nap, &collision);}
		else{*H = ' ';}
		print(path, H, T, turn, collision, nap);
		turn++;
		nap = 0; 
		collision = 0;
	}
	if (H > T){printf("Hare wins!\n");}
	if (H < T){printf("Tortoise wins!\n");}
}

/*
This moveTortoise function takes in the Tortoise pointer, Hare Pointer, and the Collision Pointer
to update the race focusing on the tortoise's position. It will generate a random integer between
1 and 3 and set it to the variable random. The turtle's address (position) will be updated in the 
array by adding the amount of spots generated by the random integer. If the turtle lands on the 
hare's position it will move back one spot and update the collision count to 1.
*/
char* moveTortoise(char* T, char* H, int *collision) 
{
	int random = 1 + (rand() % 3);
	T += random;
	if (T == H) {T--;*collision = 1;}
	return T;
}

/*
This move function takes in the path array, Tortoise Pointer, Nap Pointer, and Collision Pointer to 
update the race focusing on the hare's position. It will generate a random integer between 0 and 3 (random)
in which if it is 0 the hare will take a nap and keep it's positon. The code will then generate the
hare's movement number between 1 and 8 (random). As long as the hare is not at the end of the path (H < path + MAX)
it will check if the hare lands on a rock or stream. If they do then they will be set back the amount of spots until 
they are not on a rock or stream spot. Otherwise they will move according to their generated number.
*/
char* moveHare(char path[], char* H, char* T, int *nap, int *collision) 
{
	int random = rand() % 4;
	if (random == 0){*nap = 1;return H;}
	else
	{
		random = 1 + rand() % 8;
		if (H < path + MAX) 
		{ 
			if ((H + random) == T) {H += random - 1;*collision = 1; }
			if ((*(H + random) == 'R') || (*(H + random) == 'S')) 
			{	
				while (*(H + random) == 'R' || *(H + random) == 'S'){random--;}
				if (random == 0){return H;}
				if ((H + random) == T) { H += random - 1;*collision = 1;}
				else{H += random;}
			}
			else{H += random;}
		}
		else{H = path + MAX - 1;}
	}
	return H; 
}
 
/*
This function takes in the path pointer, hare pointer, tortoise pointer, turn value, collision value,
and nap value to print the current race update to the terminal with the required information. This code
will iterate through the path and set the data according to what the move Hare/tortoise return from their move
generation. If there is a collision in the race or the hare takes a nap it will print this as well to the terminal.
*/
void print(char* path, char* H, char* T, int turn, int collision, int nap)
{ 
	printf("Turn  %d\t ", turn); 
	while (*path < path + MAX)
	{ 
		if (H == path) {printf("H"); }
		else if (T == path) {printf("T");}
		else if (*path == 'R'){printf("R");}
		else if (*path == 'S'){printf("S");}
		else if (*path == 'C'){printf("C");}
		else{printf(" ");}
		path++;
	}
	if (nap == 1){printf("\t------NAPPING------");}
	if (collision == 1){printf("\t------COLLISION------");}
	printf("\n");
}
/*
Turn  1  HT  R  R  SSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------NAPPING------
Turn  2  HR TR  R  SSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------NAPPING------
Turn  3  HR  RT R  SSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------NAPPING------
Turn  4   R  R HRT SSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  5   R  R  RHTSSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------COLLISION------
Turn  6   R  R  R HSTSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------COLLISION------
Turn  7   R  R  R HSSSTS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------NAPPING------
Turn  8   R  R  R  SSSSSTH R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  9   R  R  R  SSSSS HTR  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------COLLISION------
Turn  10          R  R  R  SSSSS   RT RHCCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  11          R  R  R  SSSSS   R  T CHCC  R   R   CCCCCCCCCC  R  SSSS  R    ------COLLISION------
Turn  12          R  R  R  SSSSS   R  R THCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  13          R  R  R  SSSSS   R  R C CTH R   R   CCCCCCCCCC  R  SSSS  R
Turn  14          R  R  R  SSSSS   R  R C CC  T   RH  CCCCCCCCCC  R  SSSS  R
Turn  15          R  R  R  SSSSS   R  R C CC  R  TR   CHCCCCCCCC  R  SSSS  R
Turn  16          R  R  R  SSSSS   R  R C CC  R   R T CHCCCCCCCC  R  SSSS  R
Turn  17          R  R  R  SSSSS   R  R C CC  R   R  TC CCCCHCCC  R  SSSS  R
Turn  18          R  R  R  SSSSS   R  R C CC  R   R   C TCCCHCCC  R  SSSS  R
Turn  19          R  R  R  SSSSS   R  R C CC  R   R   C CCCT CCC HR  SSSS  R
Turn  20          R  R  R  SSSSS   R  R C CC  R   R   C CCCCTCCC  R HSSSS  R
Turn  21          R  R  R  SSSSS   R  R C CC  R   R   C CCCC CCT  R HSSSS  R    ------NAPPING------
Turn  22          R  R  R  SSSSS   R  R C CC  R   R   C CCCC CCC  T HSSSS  R
Turn  23          R  R  R  SSSSS   R  R C CC  R   R   C CCCC CCC  RTHSSSS  R    ------NAPPING------
Turn  24          R  R  R  SSSSS   R  R C CC  R   R   C CCCC CCC  RT SSSS  RH   ------COLLISION------
Turn  25          R  R  R  SSSSS   R  R C CC  R   R   C CCCC CCC  R TSSSS  R H
Hare wins!

Turn  1   RTHR  R  SSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  2   RT R  R HSSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------COLLISION------
Turn  3   R  T  R HSSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  4   R  R  T HSSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  5   R  R  RTHSSSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------NAPPING------     ------COLLISION------
Turn  6   R  R  R HSTSSS   R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  7   R  R  R  SSTSSH  R  R CCCC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  8   R  R  R  SSSST   R HR CCCC  R   R   CCCCCCCCCC  R  SSSS  R    ------COLLISION------
Turn  9   R  R  R  SSSSS  TR  R CCHC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  10          R  R  R  SSSSS   R TR CCHC  R   R   CCCCCCCCCC  R  SSSS  R
Turn  11          R  R  R  SSSSS   R  R TC C HR   R   CCCCCCCCCC  R  SSSS  R
Turn  12          R  R  R  SSSSS   R  R CC T HR   R   CCCCCCCCCC  R  SSSS  R    ------NAPPING------
Turn  13          R  R  R  SSSSS   R  R CC CTHR   R   CCCCCCCCCC  R  SSSS  R
Turn  14          R  R  R  SSSSS   R  R CC C  RT  R  HCCCCCCCCCC  R  SSSS  R
Turn  15          R  R  R  SSSSS   R  R CC C  R T R   CCCCCCHCCC  R  SSSS  R
Turn  16          R  R  R  SSSSS   R  R CC C  R   T   CCCCCCHCCC  R  SSSS  R
Turn  17          R  R  R  SSSSS   R  R CC C  R   R T CCCCCC CCCH R  SSSS  R
Turn  18          R  R  R  SSSSS   R  R CC C  R   R   TCCCCC CCCH R  SSSS  R    ------NAPPING------
Turn  19          R  R  R  SSSSS   R  R CC C  R   R   CTCCCC CCCH R  SSSS  R    ------NAPPING------
Turn  20          R  R  R  SSSSS   R  R CC C  R   R   CCCCTC CCCH R  SSSS  R    ------NAPPING------
Turn  21          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC TCCH R  SSSS  R    ------NAPPING------
Turn  22          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCT  RH SSSS  R    ------COLLISION------
Turn  23          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC TR HSSSS  R
Turn  24          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC  RTHSSSS  R    ------NAPPING------     ------COLLISION------
Turn  25          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC  R HTSSS  R
Turn  26          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC  R HSSTS  R
Turn  27          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC  R HSSSST R
Turn  28          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC  R HSSSS  RT
Turn  29          R  R  R  SSSSS   R  R CC C  R   R   CCCCCC CCC  R  SSSS HR T
Tortoise wins!
*/