#!/bin/bash
##########################################################
# PROPERTY OF B.J.S. INC.
##########################################################
# Group 5 CIT 470
# Johnny Rivera
# Brian Solomon
# Spencer Klump
##########################################################
# This script initialized the apache server and sets the 
# configurations that are needed with various functions.
##########################################################
exec > /root/a1/logs/logfile.log
# Yum updates and installations
function yums()
{
	yum -y update httpd
	yum -y install httpd
	yum -y install mod_ssl   
}


# Setting up Firewall for port 80 and 443
function firewallf()
{
	/bin/firewall-cmd --permanent --add-service=http
	/bin/firewall-cmd --permanent --add-service=https
	/bin/firewall-cmd --reload
}


# Starting the server/status check
function httpd_check()
{
	systemctl start httpd
	systemctl status httpd
}

# This function's purpose is to create the necessary directories that are needed and enabling per-user directories.
function directory()
{
	mkdir /var/www/html/public_html
	mkdir /etc/ssl/private
	setsebool -P httpd_enable_homedirs true
	mkdir /etc/skel/public_html
	cp /root/a1/config/certs/.htaccess /var/lib/.htaccess
	cp /root/a1/config/certs/.htaccess /var/www/html/public_html/.htaccess	
}

# This function is to organize all the overwriting files that are needed to be configured.
function overwriting()
{
	cp /root/a1/config/httpd.conf /etc/httpd/conf/httpd.conf
	cp /root/a1/config/userdir.conf /etc/httpd/conf.d/userdir.conf
	cp /root/a1/config/ssl.conf /etc/httpd/conf.d/ssl.conf
	cp /root/a1/config/certs/server.crt /etc/ssl/certs/server.crt
	cp /root/a1/config/certs/server.key /etc/ssl/private/server.key
	cp /root/a1/config/login.defs /etc/login.defs
	
}

# This function is to order the apache install so that everything gets configured smoothly.
function order()
{
	yums
	firewallf
	directory
	overwriting
	httpd_check
}
order
