#!/bin/bash
###############################################
# PROPERTY OF B.J.S. INC.
###############################################
# Group 5 CIT 470
# Spencer Klump
# Brian Solomon
# Johnny Rivera
###############################################
# This script is designed to test all monit 
# processes on the server.
###############################################

# Disable ssh and test monit for alarm state
function_sshoff()
{
	monit reload
	systemctl start monit
	systemctl stop sshd
	echo "Stopping sshd."
	#sleep 10
	#monit summary
}

# DIsable syslog and test monit for alert condition.
function_dissys()
{
	systemctl start rsyslog
	systemctl stop rsyslog
	echo "Stopping rsyslog."
	#sleep 10
	#monit summary
}

# Disable LDAP and test monit for alert.
function_stopldap()
{
	systemctl stop slapd
	echo "Stopping LDAP connection."
	#sleep 10
	#monit summary	
}

# Unmount /home to test monit alert.
function_nfsstop()
{
	systemctl stop nfs
	systemctl disable nfs
	echo "Stopping NFS service."
	#sleep 10
	#monit summary
}
# Stop Apache server to test monit.
function_apachestop()
{
	systemctl stop httpd
	echo "Stopping Apache Services."
	echo "Monit status in 25 seconds."
	sleep 25
	monit summary
}

function_sshoff
function_dissys
function_stopldap
function_nfsstop
function_apachestop
	

